### ISSUE TITLE
Movelist Search doesn't return any results for 'BT' or 'bt'

### ISSUE THREAD

**Issue by bdickason** [ndejesus1227/t7-chicken-native#47]
I can search by 1, 2, 3, etc but a search for 'BT' doesn't show any results.

To repro:
1. Tap on a character (i.e. Fang Wei)
2. Tap the search field
3. Type 'BT' (or 'bt')

Expected Result:
Moves with 'BT' show up

Current result:
No moves show up

Platform: iOS
Version: 1.0

<img width="370" alt="screen shot 2017-05-30 at 2 51 04 pm" src="https://cloud.githubusercontent.com/assets/202162/26606918/bde265ec-4548-11e7-94b4-1655dcb66e52.png">

**Comment by dxn7335** [comment]
Should be fixed with PR https://github.com/ndejesus1227/t7-chicken-native/pull/48

**Comment by bdickason** [comment]
Fixed!!!
