### ISSUE TITLE
Move data on Character page is incomplete

### ISSUE THREAD

**Issue by bdickason** [ndejesus1227/t7-chicken-native#51]
Version: iOS (Emulator)
Branch: rename

**Move Name**
I see the move data (i.e. Yoshimitsu-> in rage b+1+2) show up in the character view, but the move name just says 'move name.'

<img width="373" alt="screen shot 2017-05-31 at 11 40 42 pm" src="https://cloud.githubusercontent.com/assets/202162/26667716/5d433266-465b-11e7-915e-06603a29c534.png">

Clicking through to the actual move detail page also just says 'move name.'

<img width="364" alt="screen shot 2017-05-31 at 11 45 31 pm" src="https://cloud.githubusercontent.com/assets/202162/26667717/627f2a28-465b-11e7-94ea-c0d969ba85e2.png">

**Buttons**
The buttons for every move shows 1, 2 on both the Character view and the Move Detail page.

(see above photos)

**Damage**
The damage for Yoshimitsu's rage art shows 'null' but most other damages seem to be set correctly. Perhaps we just need to change this to 'zero' for clarity?

<img width="364" alt="screen shot 2017-05-31 at 11 45 31 pm" src="https://cloud.githubusercontent.com/assets/202162/26667726/6bd37c6e-465b-11e7-8d58-093450000381.png">

**Comment by dxn7335** [comment]
Closing now. All should be there except Move Name (open in other issue)
