### ISSUE TITLE
Warning: "Each child in an array or iterator should have a unique key prop"

### ISSUE THREAD

**Issue by bdickason** [ndejesus1227/t7-chicken-native#52]
Device: iOS (Emulator)
Branch: rename

The following warning is thrown on the Character page

<img width="375" alt="screen shot 2017-05-31 at 11 45 42 pm" src="https://cloud.githubusercontent.com/assets/202162/26667755/937a1ff2-465b-11e7-9bb5-fda10d68cc9c.png">

**Comment by dxn7335** [comment]
Fixed in past PR's
