### ISSUE TITLE
Crash when clicking 'Go Back' from About page

### ISSUE THREAD

**Issue by bdickason** [ndejesus1227/t7-chicken-native#55]
Device: iOS (Emulator)
Branch: rename

When clicking 'Go Back' on the About page, I get a crash (red screen) with the error: "undefined is not an object (evaluating '_this.props.navigator.prop') in goBack (index.js):
<img width="371" alt="screen shot 2017-05-31 at 11 51 19 pm" src="https://cloud.githubusercontent.com/assets/202162/26667914/4424aa48-465c-11e7-8d65-995c8f2d7108.png">

**Comment by bdickason** [comment]
This also happens when clicking 'Back' on the Help Out page

**Comment by dxn7335** [comment]
Fixed in past PR to flesh out about page
